CREATE TABLE "app"."investor_profiles" (
	"id" uuid PRIMARY KEY NOT NULL,
	"created_at" timestamp (6) with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp (6) with time zone DEFAULT now() NOT NULL,
	"version" integer DEFAULT 0 NOT NULL,
	"created_by" text NOT NULL,
	"updated_by" text NOT NULL,
	"investor_id" uuid NOT NULL,
	"pan_enc" "bytea" NOT NULL,
	"pan_bidx" "bytea" NOT NULL,
	"pan_last4" char(4) NOT NULL,
	"name_as_per_pan" text NOT NULL,
	"dob_enc" "bytea" NOT NULL,
	"gender" text,
	"occupation" text,
	"income_slab" text,
	"source_of_wealth" text,
	"pep_status" text,
	"pep_blocked_reason" text,
	"tax_status" text,
	"nationality" text,
	"country_of_birth" text,
	"place_of_birth_enc" "bytea",
	"tax_resident_elsewhere" boolean,
	"us_person" boolean,
	"address_line1_enc" "bytea",
	"address_line2_enc" "bytea",
	"city" text,
	"state" text,
	"pincode" char(6),
	"address_nature" text,
	"kyc_status" text DEFAULT 'UNKNOWN' NOT NULL,
	"kyc_status_check_id" uuid,
	"readiness_code" text,
	CONSTRAINT "investor_profiles_investor_id_uq" UNIQUE("investor_id"),
	CONSTRAINT "investor_profiles_pan_bidx_uq" UNIQUE("pan_bidx"),
	CONSTRAINT "investor_profiles_gender_ck" CHECK (gender IS NULL OR gender IN ('MALE', 'FEMALE', 'TRANSGENDER')),
	CONSTRAINT "investor_profiles_occupation_ck" CHECK (occupation IS NULL OR occupation IN ('BUSINESS', 'SERVICE_PRIVATE_SECTOR', 'SERVICE_PUBLIC_SECTOR', 'SERVICE_GOVERNMENT', 'PROFESSIONAL', 'AGRICULTURIST', 'RETIRED', 'HOUSEWIFE', 'STUDENT', 'FOREX_DEALER', 'OTHERS')),
	CONSTRAINT "investor_profiles_income_slab_ck" CHECK (income_slab IS NULL OR income_slab IN ('BELOW_1L', '1L_TO_5L', '5L_TO_10L', '10L_TO_25L', '25L_TO_1CR', 'ABOVE_1CR')),
	CONSTRAINT "investor_profiles_source_of_wealth_ck" CHECK (source_of_wealth IS NULL OR source_of_wealth IN ('SALARY', 'BUSINESS_INCOME', 'GIFT', 'ANCESTRAL_PROPERTY', 'RENTAL_INCOME', 'PRIZE_MONEY_OR_ROYALTY', 'OTHERS')),
	CONSTRAINT "investor_profiles_pep_status_ck" CHECK (pep_status IS NULL OR pep_status IN ('NOT_APPLICABLE', 'PEP', 'RELATED_PEP')),
	CONSTRAINT "investor_profiles_tax_status_ck" CHECK (tax_status IS NULL OR tax_status IN ('RESIDENT_INDIVIDUAL')),
	CONSTRAINT "investor_profiles_address_nature_ck" CHECK (address_nature IS NULL OR address_nature IN ('RESIDENTIAL', 'BUSINESS', 'RESIDENCE_CUM_BUSINESS')),
	CONSTRAINT "investor_profiles_kyc_status_ck" CHECK (kyc_status IN ('UNKNOWN', 'VALIDATED', 'REGISTERED', 'UNDER_PROCESS', 'ON_HOLD', 'REJECTED', 'DEACTIVATED', 'SUBMITTED')),
	CONSTRAINT "investor_profiles_pincode_ck" CHECK (pincode IS NULL OR pincode ~ '^[1-9][0-9]{5}$')
);
--> statement-breakpoint
CREATE TABLE "app"."kyc_checks" (
	"id" uuid PRIMARY KEY NOT NULL,
	"created_at" timestamp (6) with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp (6) with time zone DEFAULT now() NOT NULL,
	"version" integer DEFAULT 0 NOT NULL,
	"created_by" text NOT NULL,
	"updated_by" text NOT NULL,
	"investor_id" uuid NOT NULL,
	"purpose" text NOT NULL,
	"fp_pre_verification_id" text,
	"status" text DEFAULT 'PENDING' NOT NULL,
	"readiness_status" text,
	"readiness_code" text,
	"match_details" jsonb,
	"response_meta" jsonb,
	"next_poll_at" timestamp (6) with time zone,
	"attempts" smallint DEFAULT 0 NOT NULL,
	CONSTRAINT "kyc_checks_purpose_ck" CHECK (purpose IN ('IDENTITY', 'BANK')),
	CONSTRAINT "kyc_checks_status_ck" CHECK (status IN ('PENDING', 'PROCESSED', 'FAILED')),
	CONSTRAINT "kyc_checks_attempts_ck" CHECK (attempts >= 0)
);
--> statement-breakpoint
CREATE TABLE "app"."onboarding_applications" (
	"id" uuid PRIMARY KEY NOT NULL,
	"created_at" timestamp (6) with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp (6) with time zone DEFAULT now() NOT NULL,
	"version" integer DEFAULT 0 NOT NULL,
	"created_by" text NOT NULL,
	"updated_by" text NOT NULL,
	"investor_id" uuid NOT NULL,
	"stage" text DEFAULT 'IDENTITY' NOT NULL,
	"identity_status" text DEFAULT 'NOT_STARTED' NOT NULL,
	"profile_status" text DEFAULT 'NOT_STARTED' NOT NULL,
	"bank_status" text DEFAULT 'NOT_STARTED' NOT NULL,
	"nomination_status" text DEFAULT 'NOT_STARTED' NOT NULL,
	"risk_status" text DEFAULT 'NOT_STARTED' NOT NULL,
	"declarations_status" text DEFAULT 'NOT_STARTED' NOT NULL,
	"attest_status" text DEFAULT 'NOT_STARTED' NOT NULL,
	"provisioning_status" text DEFAULT 'NOT_STARTED' NOT NULL,
	"kyc_path" text,
	"attest_challenge_id" uuid,
	"adopted_fp_ids" jsonb,
	"provisioning_step" text,
	"provisioning_failed_reason" text,
	"otp_roundtrips" smallint DEFAULT 0 NOT NULL,
	CONSTRAINT "onboarding_applications_investor_id_uq" UNIQUE("investor_id"),
	CONSTRAINT "onboarding_applications_stage_ck" CHECK (stage IN ('IDENTITY', 'PROFILE', 'BANK', 'NOMINATION', 'RISK', 'DECLARATIONS', 'ATTEST', 'PROVISIONING', 'BLOCKED_PEP', 'KYC_UPDATE_NEEDED', 'PROVISIONING_FAILED', 'DONE')),
	CONSTRAINT "onboarding_applications_identity_status_ck" CHECK (identity_status IN ('NOT_STARTED', 'IN_PROGRESS', 'ACTION_REQUIRED', 'WAITING', 'MANUAL_REVIEW', 'DONE', 'FAILED', 'BLOCKED')),
	CONSTRAINT "onboarding_applications_profile_status_ck" CHECK (profile_status IN ('NOT_STARTED', 'IN_PROGRESS', 'ACTION_REQUIRED', 'WAITING', 'MANUAL_REVIEW', 'DONE', 'FAILED', 'BLOCKED')),
	CONSTRAINT "onboarding_applications_bank_status_ck" CHECK (bank_status IN ('NOT_STARTED', 'IN_PROGRESS', 'ACTION_REQUIRED', 'WAITING', 'MANUAL_REVIEW', 'DONE', 'FAILED', 'BLOCKED')),
	CONSTRAINT "onboarding_applications_nomination_status_ck" CHECK (nomination_status IN ('NOT_STARTED', 'IN_PROGRESS', 'ACTION_REQUIRED', 'WAITING', 'MANUAL_REVIEW', 'DONE', 'FAILED', 'BLOCKED')),
	CONSTRAINT "onboarding_applications_risk_status_ck" CHECK (risk_status IN ('NOT_STARTED', 'IN_PROGRESS', 'ACTION_REQUIRED', 'WAITING', 'MANUAL_REVIEW', 'DONE', 'FAILED', 'BLOCKED')),
	CONSTRAINT "onboarding_applications_declarations_status_ck" CHECK (declarations_status IN ('NOT_STARTED', 'IN_PROGRESS', 'ACTION_REQUIRED', 'WAITING', 'MANUAL_REVIEW', 'DONE', 'FAILED', 'BLOCKED')),
	CONSTRAINT "onboarding_applications_attest_status_ck" CHECK (attest_status IN ('NOT_STARTED', 'IN_PROGRESS', 'ACTION_REQUIRED', 'WAITING', 'MANUAL_REVIEW', 'DONE', 'FAILED', 'BLOCKED')),
	CONSTRAINT "onboarding_applications_provisioning_status_ck" CHECK (provisioning_status IN ('NOT_STARTED', 'IN_PROGRESS', 'ACTION_REQUIRED', 'WAITING', 'MANUAL_REVIEW', 'DONE', 'FAILED', 'BLOCKED')),
	CONSTRAINT "onboarding_applications_kyc_path_ck" CHECK (kyc_path IS NULL OR kyc_path IN ('EXISTING_VALID', 'NONE')),
	CONSTRAINT "onboarding_applications_otp_roundtrips_ck" CHECK (otp_roundtrips >= 0)
);
--> statement-breakpoint
CREATE INDEX "investor_profiles_kyc_status_check_idx" ON "app"."investor_profiles" USING btree ("kyc_status_check_id");--> statement-breakpoint
CREATE INDEX "kyc_checks_investor_purpose_idx" ON "app"."kyc_checks" USING btree ("investor_id","purpose");--> statement-breakpoint
CREATE INDEX "kyc_checks_pending_poll_idx" ON "app"."kyc_checks" USING btree ("next_poll_at") WHERE status = 'PENDING';