import {
  CHALLENGE_STATUSES,
  CHALLENGE_TERMINAL,
  CHALLENGE_TRANSITIONS,
} from './consent-challenge.js';
import { MANDATE_STATUSES, MANDATE_TERMINAL, MANDATE_TRANSITIONS } from './mandate.js';
import { ONBOARDING_STAGES, ONBOARDING_TERMINAL, ONBOARDING_TRANSITIONS } from './onboarding.js';
import { ORDER_STATUSES, ORDER_TERMINAL, ORDER_TRANSITIONS } from './order.js';
import {
  PAYMENT_ATTEMPT_STATUSES,
  PAYMENT_ATTEMPT_TERMINAL,
  PAYMENT_ATTEMPT_TRANSITIONS,
} from './payment-attempt.js';
import { PLAN_STATUSES, PLAN_TERMINAL, PLAN_TRANSITIONS } from './plan.js';

export interface Transition<S extends string> {
  readonly from: S;
  readonly to: S;
  readonly trigger: string;
}

export interface StateMachineDef<S extends string> {
  readonly states: readonly S[];
  readonly terminal: readonly S[];
  readonly transitions: readonly Transition<S>[];
}

export type MachineName =
  | 'ORDER'
  | 'PLAN'
  | 'MANDATE'
  | 'PAYMENT_ATTEMPT'
  | 'CHALLENGE'
  | 'ONBOARDING';

export const STATE_MACHINES: Record<MachineName, StateMachineDef<string>> = {
  ORDER: { states: ORDER_STATUSES, terminal: ORDER_TERMINAL, transitions: ORDER_TRANSITIONS },
  PLAN: { states: PLAN_STATUSES, terminal: PLAN_TERMINAL, transitions: PLAN_TRANSITIONS },
  MANDATE: {
    states: MANDATE_STATUSES,
    terminal: MANDATE_TERMINAL,
    transitions: MANDATE_TRANSITIONS,
  },
  PAYMENT_ATTEMPT: {
    states: PAYMENT_ATTEMPT_STATUSES,
    terminal: PAYMENT_ATTEMPT_TERMINAL,
    transitions: PAYMENT_ATTEMPT_TRANSITIONS,
  },
  CHALLENGE: {
    states: CHALLENGE_STATUSES,
    terminal: CHALLENGE_TERMINAL,
    transitions: CHALLENGE_TRANSITIONS,
  },
  ONBOARDING: {
    states: ONBOARDING_STAGES,
    terminal: ONBOARDING_TERMINAL,
    transitions: ONBOARDING_TRANSITIONS,
  },
};

export const TERMINAL: Record<MachineName, readonly string[]> = Object.fromEntries(
  (Object.entries(STATE_MACHINES) as [MachineName, StateMachineDef<string>][]).map(
    ([name, def]) => [name, def.terminal],
  ),
) as Record<MachineName, readonly string[]>;

export function canTransition(
  machine: MachineName,
  from: string,
  to: string,
  trigger?: string,
): boolean {
  const def = STATE_MACHINES[machine];
  return def.transitions.some(
    (t) => t.from === from && t.to === to && (trigger === undefined || t.trigger === trigger),
  );
}

const MACHINE_ORDER: readonly MachineName[] = [
  'ORDER',
  'PLAN',
  'MANDATE',
  'PAYMENT_ATTEMPT',
  'CHALLENGE',
  'ONBOARDING',
];

function renderMachine(name: MachineName, def: StateMachineDef<string>): string {
  const lines: string[] = [`## ${name}`, ''];
  lines.push(`States: ${def.states.join(', ')}`, '');
  lines.push(`Terminal: ${def.terminal.length > 0 ? def.terminal.join(', ') : '(none)'}`, '');
  lines.push('| From | Trigger | To |', '|---|---|---|');
  const sorted = [...def.transitions].sort((a, b) =>
    a.from === b.from ? a.trigger.localeCompare(b.trigger) : a.from.localeCompare(b.from),
  );
  for (const t of sorted) {
    lines.push(`| ${t.from} | ${t.trigger} | ${t.to} |`);
  }
  lines.push('');
  return lines.join('\n');
}

/** `docs/specs/states.md`, rendered from STATE_MACHINES; `scripts/gen-states.ts` writes it (RV-02-51). */
export function renderStatesDoc(): string {
  const header = [
    '<!-- GENERATED by scripts/gen-states.ts (D5). Do not edit by hand; run `pnpm gen:states`. -->',
    '',
    '# Sanchay state machines',
    '',
  ].join('\n');
  const body = MACHINE_ORDER.map((name) => renderMachine(name, STATE_MACHINES[name])).join('\n');
  return `${header}\n${body}`;
}

export {
  CHALLENGE_STATUSES,
  CHALLENGE_TERMINAL,
  CHALLENGE_TRANSITIONS,
  type ChallengeStatus,
} from './consent-challenge.js';
export {
  MANDATE_STATUSES,
  MANDATE_TERMINAL,
  MANDATE_TRANSITIONS,
  type MandateStatus,
} from './mandate.js';
export {
  ONBOARDING_STAGES,
  ONBOARDING_TERMINAL,
  ONBOARDING_TRANSITIONS,
  type OnboardingStage,
} from './onboarding.js';
export {
  type FpOrderState,
  type FpOrderStateContext,
  fpStateToOrderStatus,
  ORDER_STATUSES,
  ORDER_TERMINAL,
  ORDER_TRANSITIONS,
  type OrderStatus,
} from './order.js';
export {
  PAYMENT_ATTEMPT_STATUSES,
  PAYMENT_ATTEMPT_TERMINAL,
  PAYMENT_ATTEMPT_TRANSITIONS,
  type PaymentAttemptStatus,
} from './payment-attempt.js';
export { PLAN_STATUSES, PLAN_TERMINAL, PLAN_TRANSITIONS, type PlanStatus } from './plan.js';
