'use client';
import { useServerInsertedHTML } from 'next/navigation';
import { type ReactNode, useRef } from 'react';
import { StyleSheet } from 'react-native-web';

/** Streams react-native-web's atomic CSS into the SSR HTML so app pages render styled before hydration. */
export function RnwStyleRegistry({ children }: { children: ReactNode }): ReactNode {
  const lastEmitted = useRef('');
  useServerInsertedHTML(() => {
    const sheet = StyleSheet.getSheet();
    if (sheet.textContent === lastEmitted.current) return null;
    const first = lastEmitted.current === '';
    lastEmitted.current = sheet.textContent;
    // CSS generated by react-native-web from our own StyleSheet.create calls; no user input.
    return (
      <style
        {...(first ? { id: sheet.id } : {})}
        dangerouslySetInnerHTML={{ __html: sheet.textContent }}
      />
    );
  });
  return children;
}
